version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 500
    ignore:
      # Nuxeo stuff
      - dependency-name: "org.nuxeo*:*"

      # Stupid version numbers we don't want
      - dependency-name: "javax.inject:javax.inject"
        versions: "1.0-PFD-1"
      - dependency-name: "concurrent:concurrent"
        versions: "1.3.4-jahia6"
      - dependency-name: "commons-httpclient:commons-httpclient"
        versions: "3.1-jenkins-1"
      - dependency-name: "commons-httpclient:commons-httpclient"
        versions: "3.1-jenkins-2"
      - dependency-name: "org.apache.maven.plugins:maven-release-plugin"
        versions: "2.5.3-jahia1"
      - dependency-name: "org.apache.maven.plugins:maven-enforcer-plugin"
        versions: "1.4.2.jenkins-1"

      # Versions we don't want because they're actually older
      - dependency-name: "io.dropwizard.metrics5:metrics-bom"
        versions: "5.0.0"

      # Versions that are upgraded too often to be useful to track with dependabot
      - dependency-name: "com.amazonaws:aws-java-sdk-*"

      # Major version bumps that probably require code changes
      - dependency-name: "jline:jline"
        versions: "[1.0,)"
      - dependency-name: "commons-logging:commons-logging"
        versions: "[2.0,)"
      - dependency-name: "javax.validation:validation-api"
        versions: "[2.0,)"
      - dependency-name: "net.minidev:json-smart"
        versions: "[2.0,)"
      - dependency-name: "org.mockito:mockito-core"
        versions: "[2.0,)"
      - dependency-name: "org.hamcrest:hamcrest-*"
        versions: "[2.0,)"
      - dependency-name: "org.concordion:concordion"
        versions: "[2.0,)"
      - dependency-name: "org.fusesource.jansi:jansi"
        versions: "[2.0,)"
      - dependency-name: "org.jvnet.staxex:stax-ex"
        versions: "[2.0,)"
      - dependency-name: "org.mariadb.jdbc:mariadb-java-client"
        versions: "[2.0,)"
      - dependency-name: "net.jodah:failsafe"
        versions: "[2.0,)"
      - dependency-name: "fr.opensagres.xdocreport:fr.opensagres.xdocreport.*"
        versions: "[2.0,)"
      - dependency-name: "jboss:jboss-serialization"
        versions: "[2.0,)"
      - dependency-name: "org.jboss.el:jboss-el"
        versions: "[2.0,)"
      - dependency-name: "org.jboss:jboss-vfs"
        versions: "[3.0,)"
      - dependency-name: "org.jboss.security:jbosssx"
        versions: "[3.0,)"
      - dependency-name: "org.jboss.remoting:jboss-remoting"
        versions: "[3.0,)"
      - dependency-name: "org.apache.pdfbox:jbig2-imageio"
        versions: "[3.0,)"
      - dependency-name: "redis.clients:jedis"
        versions: "[3.0,)"
      - dependency-name: "org.javasimon:javasimon-core"
        versions: "[3.0,)"
      - dependency-name: "dnsjava:dnsjava"
        versions: "[3.0,)"
      - dependency-name: "org.easymock:easymockclassextension"
        versions: "[3.0,)"
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
        versions: "[3.0,)"
      - dependency-name: "com.google.inject:guice"
        versions: "[4.0,)"
      - dependency-name: "com.google.inject.extensions:guice-*"
        versions: "[4.0,)"
      - dependency-name: "org.awaitility:awaitility"
        versions: "[4.0,)"
      - dependency-name: "org.apache.xmlbeans:xmlbeans"
        versions: "[4.0,)"
      - dependency-name: "net.java.dev.jna:jna*"
        versions: "[5.0,)"
      - dependency-name: "org.osgi:org.osgi.*"
        versions: "[5.0,)"
      - dependency-name: "org.keycloak:keycloak-tomcat8-adapter"
        versions: "[5.0,)"
      - dependency-name: "org.apache.tomcat:*"
        versions: "[10.0,)"
      - dependency-name: "com.google.apis:google-api-services-drive"
        versions: "[v3,)"

      # TO REMOVE FROM POM
      - dependency-name: "org.apache.shindig:shindig-common"
        versions: "[2.0,)"
      - dependency-name: "org.apache.shindig:shindig-gadgets"
        versions: "[2.0,)"
      - dependency-name: "org.apache.shindig:shindig-social-api"
        versions: "[2.0,)"
      - dependency-name: "org.apache.shindig:shindig-features"
        versions: "[2.0,)"
